services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: |
      curl -Ls https://astral.sh/uv/install.sh | sh
      uv pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free

